### ISSUE TITLE
Renderer not working

### ISSUE THREAD

**Issue by bradranks** [Mermaid-Chart/issue-tracker#17] opened 2023-09-15 17:38 UTC
**Describe the bug**
Cannot use renderer
**To Reproduce**
Add renderer as first line:

%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%

**Expected behavior**
render the chart using ELK

**Screenshots**
<img width="590" alt="Screenshot 2023-09-15 at 10 33 28 AM" src="https://github.com/Mermaid-Chart/issue-tracker/assets/6288287/3c6e0f49-de32-4017-bbfc-d5880064082c">

**Desktop (please complete the following information):**
 - Mac Ventura 13.5.2 (22G91)
 - Chrome 
 - Version 116.0.5845.187 (Official Build) (arm64)

**Smartphone (please complete the following information):**

**Additional context**
It worked yesterday.

**Comment by jgreywolf** [comment] 2023-09-22 17:14
Can you share with me the full code of a diagram that is not working as expected?  When I add init to use the elk renderer I am not seeing the same error.

However, in looking at your screenshot further I am able to reproduce the error you are seeing if I do not add a newline between the init statement and the diagram type definition (graph/flowchart).

**Comment by bradranks** [comment] 2023-09-22 17:24
Hi Justin,

Thanks for looking into this, this is invaluable to us in fixing these
spaghetti monster maps from clients.
You should see some of the maps we get!
Example:
[image: image.png]

Here is the code I was using:

=======

%%{init: {"flowchart": {"defaultRenderer": "elk"}} }%%

graph LR

subgraph Marketing
SAP_Marketing_Cloud_B2B
end
subgraph Data_Sources
Other_Leads
NiceInContact
Dista
Sellout_Data_Amazon_Etailer_ME
end
subgraph Master_Data
S4HC
end

subgraph Analytics
Snowflake
Sigma
Domo
Big_Query
GravityHub
end

subgraph Authentication
Gigya
OKTA
end

subgraph CRM
C4C
end

subgraph E-Commerce
PCA_Magento_B2B-->VTEX
Shopify-->VTEX
Pro_Shopify-->VTEX
Avalara-->VTEX
D2C_Pro-->VTEX
Virtex-->VTEX
end

subgraph Learning_and_Support
Litmos
PCA_Magento_B2B-->Litmos
VTEX-->Litmos
PCA_Academy-->PCA_Magento_B2B
Salescore_Chat_bot_Margo-->PCA_Magento_B2B
PCA_Magento_B2B-->S4HC
S4HC-->Litmos
end

subgraph Supply_Chain_and_Inventory
S4HC-->VTEX
S4HC-->C4C
S4HC-->Snowflake
S4HC-->Sigma
S4HC-->Domo
S4HC-->Litmos
S4HC-->SAP_Marketing_Cloud_B2B
S4HC_Supply_Chain-->S4HC
SEI_Data_flow_tool-->S4HC
end

subgraph CRM
Gigya-->VTEX
Gigya-->BlueConic
OKTA-->Gigya
C4C-->SAP_Marketing_Cloud_B2B
C4C-->S4HC
NiceInContact-->C4C
Other_Leads-->C4C
Dista-->C4C
end

subgraph Analytics
Snowflake-->Sigma
Snowflake-->Domo
BlueConic-->Snowflake
BlueConic-->Sigma
BlueConic-->Domo
GravityHub-->Snowflake
Advertising_and_Social_Media_Data-->BlueConic
Sellout_Data_Amazon_Etailer_ME-->BlueConic
end

subgraph Marketing
Salesforce_Marketing_Cloud_DTC-->GravityHub
Physician_Locator-->Storepoint
end

=======

There is also another similar ticket opened with this test code:

=======
%%{
init: {
    "flowchart": {
        "defaultRenderer": "elk"
    }
}}%%

flowchart TB

subgraph test
       node
end
=======
Link to other ticket:
https://github.com/mermaid-js/mermaid-live-editor/issues/1305

Thanks again!

Brad

*Brad Ranks *Solutions Architect

DIRECT: 480-577-2723 |


*Technically*, The Best!

--

CONFIDENTIALITY NOTICE: This email is property of Digital, LLC and is
intended for the named person's use only. The statements and any
attachments or information disclosed in this email may be confidential,
proprietary or legally privileged.  If you are not the intended recipient,
you may not directly or indirectly disclose, copy, distribute, print or
otherwise use the contents of the information included in this email. No
confidentiality or privilege is waived or lost by any transmission errors.
If you have received this email in error, please immediately notify Digital
and destroy all electronic and hard copies of the communication, including
any attachments. This email is not an offering and is not intended to be
used for investment advice.

**Comment by jgreywolf** [comment] 2023-09-28 17:50
FYI - I have not forgotten this.  I am still working on tracking the
source of this down, and will update early next week

*Justin Greywolf*
*Software Engineer* - Mermaid Chart
https://www.mermaidchart.com

**Comment by Penagwin** [comment] 2023-10-16 17:36
Is there any update on this? My chart was working in the live editor a few weeks ago (I don't know the version sorry), but it's broken now (10.5.0).

Mine also uses nested subgraphs. It fails to render with elk. It does render with the default renderer.

**Comment by jgreywolf** [comment] 2023-10-18 17:09
This is still being looked at.  I do not have any other update yet

**Comment by jgreywolf** [comment] 2023-10-19 14:48
Looks like there is a bug in the elk renderer in mermaidJs.  We are looking into that angle now and hope to have an update by Monday

**Comment by jgreywolf** [comment] 2023-10-20 14:48
@bradranks I am happy to tell you that the elk renderer bug has been fixed. See screenshot below:

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/300077/23067cc0-5c88-4429-8f43-145b4cab45e9)

**Comment by knsv** [comment] 2023-10-26 11:40
@bradranks This was a bug in Mermaid, which has been fixed in the latest version. I am closing this issue. Please reopen if you still are having issues.

**Closed as completed by knsv** 2023-10-26 11:40 UTC
