### ISSUE TITLE
Unable to rename a diagram

### ISSUE THREAD

**Issue by oryx-it** [Mermaid-Chart/issue-tracker#19] opened 2023-10-02 20:25 UTC
I'm unable to change the name of a diagram.

I'm using a macOS 15.3.2

https://github.com/Mermaid-Chart/issue-tracker/assets/111514654/d65811be-efda-4939-bb16-29dd83490d9e

**Comment by jipock-morgan** [comment] 2023-10-03 14:43
This is also happening to me - running Windows 11 / Microsoft Edge (116.0.1938.9).

**Comment by DavidCampbell-architect** [comment] 2023-10-04 14:32
This happens to me as well. A workaround is to rename from the settings menu of the diagram.
I'm running Windows 11, Brave Version 1.58.135 Chromium: 117.0.5938.140

**Comment by nirname** [comment] 2023-10-04 17:59
Confirmed. The title of the diagram is not saved. After editing and going back to the diagrams list it is visible, but when you go back to editing you get "Untitled diagram" again
![image (13)](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/beb2ac7b-28b5-431e-a7d4-a53a77af943b)
![image (14)](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/e57bbf39-1775-4b0b-bb66-df0d1158883b)

**Comment by pbrolin47** [comment] 2023-10-11 09:36
We did a fix related to diagram naming last week. Are you still having problems with this issue? Best regards, Per

**Comment by nirname** [comment] 2023-10-11 10:18
It works.

But then again there is undesirable "Untitled diagram" text in the diagram name input. Plus when switching keyboard layout input loses focus. Perhaps these are 2 separate issues (apart from that one)

**Comment by oryx-it** [comment] 2023-10-11 10:28
I don't how you're testing but it's still not working. The worst performing and most buggy product is the paid one :-(


https://github.com/Mermaid-Chart/issue-tracker/assets/111514654/f067f9cd-df51-4c14-8cfb-357860466a1b

**Comment by DavidCampbell-architect** [comment] 2023-10-11 16:27
I still have the same problem as well. The only way to change the name is from the settings window for the diagram. Changing the name does not work if you change from within the diagram page.

**Comment by pbrolin47** [comment] 2023-10-26 12:27
Tested renaming of diagrams from within the digram page today. Unfortunately, I could not reproduce the problem. 
[screen-capture.webm](https://github.com/Mermaid-Chart/issue-tracker/assets/114684273/53bec18f-0340-4e82-9bfd-ba9e820b02ef)

**Comment by nirname** [comment] 2023-10-26 20:02
Looks as if it is resolved, cannot reproduce either. Do you guys use integration tests? This case is a good candidate for that

**Comment by pbrolin47** [comment] 2023-10-27 09:15
Closing. Will reopen if needed

**Closed as completed by pbrolin47** 2023-10-27 09:15 UTC
