### ISSUE TITLE
Cannot rename presentation by double clicking in the highlighted area

### ISSUE THREAD

**Issue by nirname** [Mermaid-Chart/issue-tracker#33] opened 2023-10-04 18:57 UTC
**Describe the bug**

I have created a presentation, gave it a name, and now I am trying to rename it. I double click on the highlighted area, but nothing happens. To rename it I must be precise and double click exactly on its name. Otherwise this does not work.

**To Reproduce**

1. Create arbitrary presentation
2. Give it a name
3. Try editing the name, by double-clicking the field, but not title itself.

The title is displayed as if it is available for editing, whereas it is not

**Expected behavior**

I am able to change the title of the presentation by double clicking the field that is highlighted.

**Screenshots**

My screenshot tool did not capture, but I see border around the inputs. As you can see, my cursor is not pointing at the title itself, but in the interface I see border as if it is editable.

![image](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/232f6775-524c-4c5c-a5c3-cbaf29467b3d)
![image](https://github.com/Mermaid-Chart/issue-tracker/assets/2842432/173ba714-4a86-4b77-8d8e-daccc0ae633f)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version 117.0.5938.132 (Official Build) (64-bit)

**Comment by pbrolin47** [comment] 2023-10-11 08:32
Thank you for the feedback. We will take the issue into consideration when planning future releases

**Comment by jgreywolf** [comment] 2023-10-25 02:22
FYI - I am not able to reproduce this.

I should clarify, if I double click outside the boundaries of the text, but within the borders as you mentioned, then it does appear to be inconsistent.

However, if I only click once within the bordered area, it goes straight into editor

**Comment by nirname** [comment] 2023-10-26 20:20
Yes, this does not hinder the job, but that is a deviation from what is expected.

**Comment by jgreywolf** [comment] 2023-11-25 20:40
@nirname I am going to close this item, as we are tracking internally.
We have a suite of improvements planned for presentations that we will be rolling out incrementally over the 1-2 months

**Closed as completed by jgreywolf** 2023-11-25 20:40 UTC

**Comment by nirname** [comment] 2023-11-26 11:00
Ok
